#EXPERIMENT 10
#ROHAN KUMBHAR
#ENTC A2
#02/02/26
#PRN:-25070123141
#CREATING DATASET AND LOAD DATASET

In [ ]:
# Dataset creation
import pandas as pd

data= {
    "Roll_No": [101,102,103,104,105],
    "Gender":["Female","Male","Female","Male","Female"],
    "Department":["Computer","IT","ENTC","Mechanical","Computer"],
    "CGPA":[8.2,7.5,9.1,6.8,8.7],
    "Name":["Darsh","Aadi","Viraj","Vidhaan","Saksham"]
}
df = pd.DataFrame(data)

df.to_csv("students.csv", index=False)
df

   Roll_No  Gender  Department  CGPA     Name
0      101  Female    Computer   8.2    Darsh
1      102    Male          IT   7.5     Aadi
2      103  Female        ENTC   9.1    Viraj
3      104    Male  Mechanical   6.8  Vidhaan
4      105  Female    Computer   8.7  Saksham

In [ ]:
#Finding shape
df.shape

(5, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   Name        5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [ ]:
df.describe()

          Roll_No     CGPA
count    5.000000  5.00000
mean   103.000000  8.06000
std      1.581139  0.92358
min    101.000000  6.80000
25%    102.000000  7.50000
50%    103.000000  8.20000
75%    104.000000  8.70000
max    105.000000  9.10000

In [ ]:
# CGPA OF ROLL_NO 105
cgpa_105 = df[df['Roll_No'] == 105]['CGPA'].iloc[0]
print(f"The CGPA of Roll_No 105 is: {cgpa_105}")

The CGPA of Roll_No 105 is: 8.7

In [ ]:
# CGPA OF TOPPER
topper = df.loc[df['CGPA'].idxmax()]
print(f"The topper is {topper['Name']} with a CGPA of {topper['CGPA']}.")

The topper is Viraj with a CGPA of 9.1.

In [ ]:
# DELETE GENDER COLUMN
df = df.drop('Gender', axis=1)
display(df)

   Roll_No  Department  CGPA     Name GRADE
0      101    Computer   8.2    Darsh     A
1      102          IT   7.5     Aadi    B+
2      103        ENTC   9.1    Viraj    A+
3      104  Mechanical   6.8  Vidhaan     B
4      105    Computer   8.7  Saksham     A

In [ ]:
# INSERT A NEW COLUMN GRADE
def assign_grade(cgpa):
    if cgpa >= 9.0:
        return 'A+'
    elif cgpa >= 8.0:
        return 'A'
    elif cgpa >= 7.0:
        return 'B+'
    elif cgpa >= 6.0:
        return 'B'
    else:
        return 'C'

df['GRADE'] = df['CGPA'].apply(assign_grade)
display(df)

   Roll_No  Gender  Department  CGPA     Name GRADE
0      101  Female    Computer   8.2    Darsh     A
1      102    Male          IT   7.5     Aadi    B+
2      103  Female        ENTC   9.1    Viraj    A+
3      104    Male  Mechanical   6.8  Vidhaan     B
4      105  Female    Computer   8.7  Saksham     A

In [ ]:
# PERFORM MEAN, MEDIAN, MODE OPERATION

print("Mean of numerical columns:")
display(df.mean(numeric_only=True))

print("\nMedian of numerical columns:")
display(df.median(numeric_only=True))

print("\nMode of each column:")
for column in df.columns:
    print(f"Mode of {column}:")
    display(df[column].mode())

Mean of numerical columns:

Roll_No    103.00
CGPA         8.06
dtype: float64

Median of numerical columns:

Roll_No    103.0
CGPA         8.2
dtype: float64

Mode of each column:
Mode of Roll_No:

0    101
1    102
2    103
3    104
4    105
Name: Roll_No, dtype: int64

Mode of Gender:

0    Female
Name: Gender, dtype: object

Mode of Department:

0    Computer
Name: Department, dtype: object

Mode of CGPA:

0    6.8
1    7.5
2    8.2
3    8.7
4    9.1
Name: CGPA, dtype: float64

Mode of Name:

0       Aadi
1      Darsh
2    Saksham
3    Vidhaan
4      Viraj
Name: Name, dtype: object

In [ ]:
# Access information of ROLL_NO 103
roll_no_103_info = df[df['Roll_No'] == 103]
display(roll_no_103_info)

   Roll_No  Gender Department  CGPA   Name
2      103  Female       ENTC   9.1  Viraj

In [ ]:
# Access information of Column Department
print("Unique departments and their counts:")
print(df['Department'].value_counts())

print("\nAll unique departments:")
print(df['Department'].unique())

Unique departments and their counts:
Department
Computer      2
IT            1
ENTC          1
Mechanical    1
Name: count, dtype: int64

All unique departments:
['Computer' 'IT' 'ENTC' 'Mechanical']

In [ ]:
# FIND OUT DATATYPE OF EACH COLUMN
display(df.dtypes)

Roll_No         int64
Gender         object
Department     object
CGPA          float64
Name           object
dtype: object

In [ ]:
#UPLOAD THE DATASET
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.size

930

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
df.shape

(93, 10)

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0